version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "prettier"
    groups:
      shiki:
        patterns:
          - "shiki"
          - "@shikijs/transformers"
      next:
        patterns:
          - "next"
          - "@next/*"
          - "eslint-config-next"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_TOKEN}}
