name: Validate

on: [push]

env:
  NODE_VERSION: 20
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate props
        run: npm run docs:generate

      - name: Lint
        run: npm run lint -- --max-warnings 0

      - name: Typecheck
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate props
        run: npm run docs:generate

      - name: Build
        run: npm run build

  release:
    needs: [main, build]
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    environment:
      name: Documentation
      url: ${{ steps.deployment.outputs.page_url }}
    timeout-minutes: 30
    if: ${{ contains('refs/heads/main', github.ref) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate props
        run: npm run docs:generate

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "out/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
